version: "3.6"
services:
  develop:
    stdin_open: true
    container_name: platform-developer-docs
    image: platform-developer-docs-dev:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src # Links the source files to the running container
    ports:
      - 8000:8000
